name: Build and publish Jekyll site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1" # recommended; keeps google-protobuf compatibility

      - name: Install bundler and rake (ensure rake executable exists)
        run: |
          gem install bundler -v 2.5.23

      - name: Install gems with bundler
        run: |
          bundle install

      - name: Build site with Jekyll (use bundle exec to ensure gems from Bundler are used)
        run: bundle exec jekyll build --destination ./_site

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
